export const PROJECT_FORM = "PROJECT_FORM";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECTS";
export const VERIFY_FORM = "VERIFY_FORM";
export const SELECT_PROJECT = "SELECT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";